version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - broker
      - database


  proxy:
    build: docker/nginx/.
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf'
      - './static:/static'
    ports:
      - '80:80'
    depends_on:
      - web


  database:
    image: 'postgres'
    environment:
      - POSTGRES_USER=webvita
      - POSTGRES_DB=webvita