# Generated by Django 2.0.1 on 2018-02-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='scripts',
        ),
        migrations.AddField(
            model_name='resume',
            name='script',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ResumeScript'),
        ),
    ]
