# Generated by Django 2.0.1 on 2018-02-06 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20180206_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='resumefield',
            name='markup',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resumelayout',
            name='markup',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resumescript',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resumetheme',
            name='styletext',
            field=models.TextField(default=''),
        ),
    ]
